name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  cd:
    name: CD
    needs: ci
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/cd.yml
    secrets: inherit